before_install: 
    - sudo apt-get update -qq
    - sudo apt-get install -y libnet1-dev
    - sudo apt-get install -y libpcap-dev 

language: c

os: linux

compiler: gcc

env:
    - AUTOTOOLS=no COVERAGE=no BUILD=static

script:     make all
